package com.harness.pipeline.enums;

public enum RuleConditionField {
  REQUEST_METHOD,
  REQUEST_HOST,
  REQUEST_PATH,
  REQUEST_QUERY_STRING,
  REQUEST_HEADER,

  RESPONSE_STATUS_CODE,
  RESPONSE_STATUS_CLASS,
  RESPONSE_TIME_MS,
  RESPONSE_HEADER,

  METADATA_ENVIRONMENT,
  METADATA_REGION,
  METADATA_TAG
}
